site_name: AusPolls
site_description: Australia Polling
edit_uri: edit/main/docs

repo_url: https://github.com//
repo_name: /

theme:
  name: material
  icon:
    repo: fontawesome/brands/github 
  features:
    - content.action.edit
